### ISSUE TITLE
Add logging and registering functionality

### ISSUE THREAD

**Issue by jrobertgardzinski** [jrobertgardzinski/LendingLibrary#4]
## Task description

Think about adding functionality of registering new users and logging into system. Plan privileges of users.

## Tasks

- [ ] Find suitable framework / library
- [ ] Design users privileges
- [ ] Implement register functionality
- [ ] Implement logging in functionality
